language: php
php:
  - 5.6
  - 7
  - hhvm
  - nightly

install:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - php vendor/bin/coveralls -vvv

notifications:
  email:
    - martin.aarhof@gmail.com
